worker_processes 1;

events {
    worker_connections 1024;
}

http {
    include mime.types;
    default_type application/octet-stream;

    sendfile on;

    # Список серверов, куда будут проксироваться запросы.
    upstream backend {
        #Round Robin(стандартный) - равномерное распределние c учётом веса серверов
        #IP Hash(ip_hash) - сервер определяется по ip адресу клиента. Гарантирует, что запросы с одного и того же адреса попадают на один и тот же сервер
        #Generic Hash(hash) - сервер определяется по пользовательскому ключу
        #least_time(+ параметр: header(Время получения первого байта от сервера), last_byte(Время получения полного ответа от сервера),
          #last_byte inflight(Время получения полного ответа от сервера с учетом неполных запросов))-Сервер с наименьшей средней задержкой и наименьшим количеством подключений
        #random - случайный. Если есть two параметр, то выбирает 2 с учётом веса, а потом из них с помощью метода
        # Least Connections - Отправляем запрос на сервер с наименьшим количеством активных соединений
        least_conn;
        server host.docker.internal:5001;
        server host.docker.internal:5002;
        server host.docker.internal:5003;
        server host.docker.internal:5004;
    }

    # 8080 порт - точка входа для пользователей
    server {
        listen 8080;
        server_name localhost;

        location / {
            proxy_pass http://backend;
        }
    }

    # http-сервер на 5001 порту всегда возвращает строку "5001"
    server {
        listen 5001;

        location / {
            return 200 '5001';
            add_header Content-Type text/plain;
        }
    }

    # http-сервер на 5002 порту всегда возвращает строку "5002"
    server {
        listen 5002;

        location / {
            return 200 '5002';
            add_header Content-Type text/plain;
        }
    }
}